const tree = [
  {
    id: 1,
    firstName: "Vito",
    lastName: "Corleone",
    sex: "M",
    birthYear: 1892,
    deathYear: 1954,
    motherId: null,
    fatherId: null,
    spouseId: 2,
  },
  {
    id: 2,
    firstName: "Carmella",
    lastName: "Not-Corleone", // ???
    sex: "F",
    birthYear: 1897,
    deathYear: 1959,
    motherId: null,
    fatherId: null,
    spouseId: 1,
  },
  {
    id: 3,
    firstName: "Sonny",
    lastName: "Corleone",
    sex: "M",
    birthYear: 1916,
    deathYear: 1948,
    motherId: 2,
    fatherId: 1,
    spouseId: null,
  },
  {
    id: 4,
    firstName: "Fredo",
    lastName: "Corleone",
    sex: "M",
    birthYear: 1919,
    deathYear: 1959,
    motherId: 2,
    fatherId: 1,
    spouseId: null,
  },
  {
    id: 5,
    firstName: "Michael",
    lastName: "Corleone",
    sex: "M",
    birthYear: 1920,
    deathYear: 1997,
    motherId: 2,
    fatherId: 1,
    spouseId: 7,
  },
  {
    id: 6,
    firstName: "Connie",
    lastName: "Corleone",
    sex: "F",
    birthYear: 1927,
    deathYear: null,
    motherId: 2,
    fatherId: 1,
    spouseId: null,
  },
  {
    id: 7,
    firstName: "Kay",
    lastName: "Adams",
    sex: "F",
    birthYear: 1934,
    deathYear: null,
    motherId: null,
    fatherId: null,
    spouseId: 5,
  },
];

alert("hi");
